version: '2'
services:
  testrpc:
    image: dougvk/mydapp_testrpc
    command: bash -c "testrpc -h 0.0.0.0"
    ports:
      - "7000:8545"
  truffle3:
    image: dougvk/truffle3:latest
    command: bash
    stdin_open: true
    tty: true
    ports:
      - "7002:8080"
    volumes_from:
      - truffle_vol
  truffle_vol:
    image: busybox
    container_name: truffle_vol
    volumes:
      - ./src:/app

volumes:
  truffle_vol:
